micronaut:
  application:
    name: pacBatch
endpoints:
  health:
    enabled: true
    sensitive: false
#tag::otel[]
otel:
  traces:
    exporter: otlp
    propagator: tracecontext, baggage, xray
    exclusions: /health
#end::otel[]
netty:
  default:
    allocator:
      max-order: 3
#tag::dynamodb[]
dynamodb:
  table-name: 'bookcatalogue'
#end::dynamodb[]
---
#tag::thumbnail[]
thumbnail:
  width: 256
  height: 256
#end::thumbnail[]